dojo.provide("plugins.core.reload");

dojo.reload("plugins.core.Agua.Data");
dojo.reload("plugins.core.Agua.Access");
dojo.reload("plugins.core.Agua.App");
dojo.reload("plugins.core.Agua.Ami");
dojo.reload("plugins.core.Agua.Aws");
dojo.reload("plugins.core.Agua.Cloud");
dojo.reload("plugins.core.Agua.Cluster");
dojo.reload("plugins.core.Agua.Feature");
dojo.reload("plugins.core.Agua.File");
dojo.reload("plugins.core.Agua.Group");
dojo.reload("plugins.core.Agua.Hub");
dojo.reload("plugins.core.Agua.Package");
dojo.reload("plugins.core.Agua.Parameter");
dojo.reload("plugins.core.Agua.Project");
dojo.reload("plugins.core.Agua.Report");
dojo.reload("plugins.core.Agua.Shared");
dojo.reload("plugins.core.Agua.Sharing");
dojo.reload("plugins.core.Agua.Source");
dojo.reload("plugins.core.Agua.Stage");
dojo.reload("plugins.core.Agua.StageParameter");
dojo.reload("plugins.core.Agua.User");
dojo.reload("plugins.core.Agua.View");
dojo.reload("plugins.core.Agua.Workflow");
dojo.reload("plugins.core.Common.Array");
dojo.reload("plugins.core.Common.ComboBox");
dojo.reload("plugins.core.Common.Date");
dojo.reload("plugins.core.Common.Text");
dojo.reload("plugins.core.Common.Sort");
dojo.reload("plugins.core.Common.Toast");
dojo.reload("plugins.core.Common.Util");
dojo.reload("plugins.core.Common");
dojo.reload("plugins.core.Agua");

dojo.declare( "plugins.core.reload", [], {});
