// REGISTER MODULE PATHS
dojo.registerModulePath("doh","../../dojo/util/doh");	
dojo.registerModulePath("plugins","../../plugins");	
dojo.registerModulePath("t","../../t/unit");	

// DOJO TEST MODULES
//dojo.require("dijit.dijit");
////dojo.require("dojox.robot.recorder");
////dojo.require("dijit.robot");
dojo.require("doh.runner");

// Agua TEST MODULES
dojo.require("t.doh.util");

// DEBUG LOADER
//dojo.require("dojoc.util.loader");

// TESTED MODULES
dojo.require("plugins.core.Agua");
dojo.require("plugins.folders.Folders");
dojo.require("plugins.folders.ProjectFiles");

// GLOBAL VARIABLES
var Agua;
var Data;
var data;

dojo.addOnLoad(function(){


Agua = new plugins.core.Agua( {
	cgiUrl 		:	dojo.moduleUrl("plugins", "../../../cgi-bin/agua/")
	, database	: 	"aguatest"
	, dataUrl	: 	"getData-execute.json"
});
Agua.cookie('username', 'testuser');
Agua.cookie('sessionid', '9999999999.9999.999');
Agua.loadPlugins([
	"plugins.data.Controller",
	"plugins.workflow.Controller"
]);

// CREATE TAB
Agua.controllers["workflow"].createTab();

var workflow = Agua.controllers["workflow"].tabPanes[0];
console.log("runTests    workflow: ");
console.dir({workflow:workflow});
var runStatus = workflow.core.runStatus;
console.log("runTests    runStatus: " + runStatus);

// CREATE RUNNER
var runner = new Object;
runner.project = "Project1";
runner.workflow = "Workflow1";
runner.number = 1;
runner.childNodes = workflow.core.userWorkflows.dropTarget.getAllNodes();
console.log("runTests    runner: " + runner);

console.log("runTests    BEFORE runStatus.runWorkflow");
runStatus.runWorkflow(runner);
console.log("runTests    AFTER runStatus.runWorkflow");

console.log("runTests    Doing doh.register('dojox.robot.AutoGeneratedTestGroup'");

doh.register('dojox.robot.AutoGeneratedTestGroup',{
	name: 'autotest0',
	timeout: 20750,
	runTest: function(){

		// ROBOT TURNED OFF
		doh.assertTrue(true);
		
		console.log("runTests    autotest0    BEFORE d = new doh.Deferred()");
		var d = new doh.Deferred();

		// ROBOT START HERE
		// NB: doh.robot._mouseMove(x, y, absolute, duration);
		//console.log("runTests    autotest0    BEFORE moves")
		// doh.robot.mouseMove(470, 226, 696, 100, true);
		//console.log("runTests    autotest0    AFTER FIRST mouseMove")
		// doh.robot.mouseMove(549, 220, 907, 100, true);
		//
		// doh.robot.mouseMoveAt(function(){ return document.getElementsByTagName('TD')[123]; }, 138, 100, 45, 14);
		//console.log("runTests    autotest0    AFTER FIRST mouseMoveAt")
		// doh.robot.mouseClick({left:true, middle:false, right:false}, 1);
		//console.log("runTests    autotest0    AFTER FIRST mouseClick")
		// doh.robot.mouseMove(647, 254, 647, 100, true);
		// doh.robot.mouseMoveAt(function(){ return document.getElementsByTagName('TD')[128]; }, 212, 100, 17, 18);
		// doh.robot.mouseClick({left:true, middle:false, right:false}, 1);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_0', 11);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_1', 1);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_2', 1);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_3', 1);
		//
		//console.log("runTests    autotest0    AFTER scrollIntoView")
		//
		// doh.robot.mouseMove(199, 206, 7018, 100, true);
		// doh.robot.mouseMoveAt('dojoUnique23', 1608, 100, 74, 10);
		// doh.robot.mouseClick({left:true, middle:false, right:false}, 1);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_4', 9);
		// doh.robot.scrollIntoView('plugins_files__GroupDragPane_4', 5247);
		// doh.robot.mouseMove(385, 35, 3467, 100, true);
		// doh.robot.mouseMove(383, 41, 1005, 100, true);
		// doh.robot.mouseMoveAt('dojoUnique12_underlay', 34, 100, 383, 41);
		// doh.robot.mouseClick({left:true, middle:false, right:false}, 1);
		//
		//console.log("runTests    autotest0    AFTER moves")
		//
		// doh.robot.sequence(function(){
		//	  if( 1 ) {
		//		   console.log("runTests    autotest0    Before d.callback(true)")
		//		   d.callback(true);
		//	  }
		//	  else
		//	  {
		//		   d.errback(new Error('runTests    autotest0    Error'));
		//	  }
		// }, 1000);


		// ROBOT TURNED OFF
		d.callback(true);
		
		return d;
	}
});

doh.run();


	
}); // FIRST dojo.addOnLoad


