
---
test:
    TESTUSER:       testuser
    TESTPASSWORD:   testpassword
    TESTDATABASE:   testdatabase

database: wgspipe
hostname: 'ussd-dev-lndb01.illumina.com'
username: pcruz
password: zorbas
error_rate_read2: 2
error_rate_read1: 1.5
min_q30plus_yield: 80
estimated_per_align: 80

#quality of lanes to use 
min_per_good_tiles: 1
max_read1_phiX_error_rate: 2.0
max_read2_phiX_error_rate: 3.0
min_read1_per_q30: 65
min_read2_per_q30: 65

# estimate factor per lane align yield
avg_align_yield_per_lane_Gb: 35
avg_yield_trimmed_gb: 35


#build limits
build_launch_limit: 5


#casava cloud
casava_cloud_concurrent_limit: 75 
casava_cloud_24hours_limit: 50



#qc quality of builds
build_qc_normal_samples:
    gt_gen_concordance:
        - ge
        - 0.9924
    casava_duplicates_percent:
        - le
        - 0.05
    casava_snp_het_hom_ratio:
        - le
        - 2.1
    casava_coverage_autosomal_coverage:
        - ge
        - 0.98
    depth_per_1X:
        - ge
        - 0.9785
    depth_per_10X: 
        - ge
        - 0.9485
    gb_q30: 
        - ge
        - 80.0
    per_q30:
        - ge
        - 0.80
    contam_hom_fraction_bad: 
        - le
        - 0.05
    gt_gen_usage:
        - ge
        - 0.97
    consensus_exon_coverage:
        - ge
        - 0.97
    insert_median:
        - ge
        - 240
    exon_depth_per_1X:
        - ge
        - 0.97
    exon_depth_per_10X:
        - ge
        - 0.95



#qc quality of cancer samples
build_qc_cancer_samples:
    gt_gen_concordance:
        - ge
        - 0.991
    casava_duplicates_percent:
        - le
        - 0.05
    casava_snp_het_hom_ratio:
        - le
        - 2.1
    casava_coverage_autosomal_coverage:
        - ge
        - 0.98
    depth_per_1X:
        - ge
        - 0.9785
    depth_per_10X:
        - ge
        - 0.9485
    gb_q30:
        - ge
        - 80.0
    per_q30:
        - ge
        - 0.80
    contam_hom_fraction_bad:
        - le
        - 0.05
    gt_gen_usage:
        - ge
        - 0.97
    consensus_exon_coverage:
        - ge
        - 0.97
    insert_median:
        - ge
        - 240
    exon_depth_per_1X:
        - ge
        - 0.97
    exon_depth_per_10X:
        - ge
        - 0.95


#error emails
error_emails:
    - pcruz@illumina.com
    - bsickler@illumina.com
    - sajay@illumina.com
    - knobuta@illumina.com
    - amaroo@illumina.com


#align info
info_emails:
    - pcruz@illumina.com
    - bsickler@illumina.com
    - sajay@illumina.com
    - JBernd@illumina.com
    - mye@illumina.com
    - lgomez@illumina.com
    - kgietzen@illumina.com
    - kviaud@illumina.com
    - knobuta@illumina.com


debug_emails:
    - pcruz@illumina.com

lab_emails:
    - JBernd@illumina.com
    - mye@illumina.com
    - lgomez@illumina.com
    - pcruz@illumina.com
    - kgietzen@illumina.com
    - kviaud@illumina.com
    - tmcsherry@illumina.com

clia_emails:
    - pcruz@illumina.com
    - ylyan@illumina.com
    - sjain@illumina.com
    - jhurless@illumina.com
    - sajay@illumina.com

cloud_emails:
    -IlluminaServicesCloud@illumina.com


target_to_lane_count:
    30: 3 
    40: 4
    50: 5 
    60: 5
    80: 7
    90: 8
    220: 5
    110: 3
    145: 4
   

#aligned values 
target_to_yield:
    30: 90000 
    40: 112000
    50: 140000
    60: 170000
    80: 240000
    90: 260000    
    220: 220000
    110: 110000
    145: 145000   
 
sge_align_opts: '-q prod.q'    
sge_queue: 'prod.q'    
# this maybe multiple places    
# This is used to populate the initial flowcell location
# by searching the file system

run_root: 
    - /illumina/upload/services
   
   
   
#project defaults
build_version: NCBI37
dbsnp_version: 131
build_root: /illumina/build/services/Projects
build_type: local
launch_limit: 5
scratch_root: /illumina/scratch/services
include_NPF: n

#pl config default parameters
pipeline_root: /illumina/software/OLB/OLB-1.9.2/bin
casava_root: /illumina/development/casava/CASAVA-VariantCalling-2.12a_gVCF
bcl_converter_bin: /illumina/development/casava/CASAVA-1.8.3a3/bin/configureBclToFastq.pl
bcl_options: "--force --ignore-missing-control --ignore-missing-stats " 
pl_wrapper_root: /illumina/scripts/WGS/PL_wrapper/PLW-1.8
python_tools: /illumina/scripts/WGS/python_tools
tools: /illumina/scripts/WGS/tools/bin
align_retries: 2
align_nproc_per_lane: 4    
bcl_nproc_per_lane: 4

#archiving
archive_pending: /illumina/scratch/services/archive/pending
genotype_source_dir: /illumina/scratch/Genotyping_Data/InstituteReports/WGS_GenotypingReports
gt_deliv_src: /illumina/scratch/Genotyping_Data/InstituteReports/WGS_GT_Deliverables   
# fasta locations defaults
fasta_locations:
    NCBI37_XY: /illumina/scratch/services/Genomes/FASTA_UCSC/HumanNCBI37_XY/HumanNCBI37_XY.fa
    NCBI37_XX: /illumina/scratch/services/Genomes/FASTA_UCSC/HumanNCBI37_XX/HumanNCBI37_XX.fa
    NCBI36_XY: /illumina/scratch/services/Genomes/FASTA_UCSC/HumanNCBI36_XY/HumanNCBI36_XY.fa
    NCBI36_XX: /illumina/scratch/services/Genomes/FASTA_UCSC/HumanNCBI36_XY/HumanNCBI36_XX.fa
