//>>built
require({cache:{"JBrowse/Store/SeqFeature/BigWig/Window":function(){define(["dojo/_base/declare","dojo/_base/lang","./RequestWorker"],function(l,o,f){return l(null,{constructor:function(f,i,n,j){this.bwg=f;this.cirTreeOffset=i;this.cirTreeLength=n;this.isSummary=j},BED_COLOR_REGEXP:/^[0-9]+,[0-9]+,[0-9]+/,readWigData:function(f,i,n,j,o){(f=this.bwg.refsByName[f])?this.readWigDataById(f.id,i,n,j,o):j([])},readWigDataById:function(h,i,n,j,l){this.cirHeader?(new f(this,h,i,n,j,l)).cirFobRecur([this.cirTreeOffset+
48],1):(h=o.hitch(this,"readWigDataById",h,i,n,j),this.cirHeaderLoading?this.cirHeaderLoading.push(h):(this.cirHeaderLoading=[h],this.bwg.data.slice(this.cirTreeOffset,48).fetch(o.hitch(this,function(f){this.cirHeader=f;this.cirBlockSize=(new Int32Array(this.cirHeader,0,2))[1];dojo.forEach(this.cirHeaderLoading,function(b){b()});delete this.cirHeaderLoading}),l)))}})})},"JBrowse/Store/SeqFeature/BigWig/RequestWorker":function(){define(["dojo/_base/declare","dojo/_base/lang","JBrowse/Model/Range",
"jszlib/inflate","jszlib/arrayCopy"],function(l,o,f,h,i){var n=function(){console.log.apply(console,arguments)},j=l(null,{get:function(b){return this[{start:"min",end:"max",seq_id:"segment"}[b]||b]},tags:function(){return"start,end,seq_id,score,type,source".split(",")}}),u=l(j,{}),s=l(j,{});return l(null,{BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(b,e,a,c,g,d){this.window=b;this.source=b.bwg.name||void 0;this.blocksToFetch=[];this.outstanding=0;this.chr=e;
this.min=a;this.max=c;this.callback=g;this.errorCallback=d||function(a){console.error(a,a.stack,arguments.caller)}},cirFobRecur:function(b,e){this.outstanding+=b.length;for(var a=4+32*this.window.cirBlockSize,c,g=0;g<b.length;++g){var d=new f(b[g],Math.min(b[g]+a,this.window.cirTreeOffset+this.window.cirTreeLength));c=c?c.union(d):d}a=c.ranges();for(c=0;c<a.length;++c)this.cirFobStartFetch(b,a[c],e)},cirFobStartFetch:function(b,e,a){e.max();e.min();this.window.bwg.data.slice(e.min(),e.max()-e.min()).fetch(o.hitch(this,
function(c){for(var g=0;g<b.length;++g)e.contains(b[g])&&(this.cirFobRecur2(c,b[g]-e.min(),a),--this.outstanding,0==this.outstanding&&this.cirCompleted())}),this.errorCallback)},cirFobRecur2:function(b,e,a){var c=new Int8Array(b),g=new Int16Array(b),b=new Int32Array(b),c=c[e],g=g[e/2+1],e=e+4;if(0!=c)for(c=0;c<g;++c){var d=e/4,f=b[d],h=b[d+1],i=b[d+2],m=b[d+3],n=b[d+4]<<32|b[d+5],a=b[d+6]<<32|b[d+7];(f<this.chr||f==this.chr&&h<=this.max)&&(i>this.chr||i==this.chr&&m>=this.min)&&this.blocksToFetch.push({offset:n,
size:a});e+=32}else{for(var j=[],c=0;c<g;++c)d=e/4,f=b[d],h=b[d+1],i=b[d+2],m=b[d+3],n=b[d+4]<<32|b[d+5],(f<this.chr||f==this.chr&&h<=this.max)&&(i>this.chr||i==this.chr&&m>=this.min)&&j.push(n),e+=24;0<j.length&&this.cirFobRecur(j,a+1)}},cirCompleted:function(){this.blocksToFetch.sort(function(b,e){return(b.offset|0)-(e.offset|0)});0==this.blocksToFetch.length?this.callback([]):(this.features=[],this.tramp())},createFeature:function(b,e,a){a||(a={});var c=new u;c.segment=(this.window.bwg.refsByNumber[this.chr]||
{}).name;c.min=b;c.max=e;c.type="remark";c.source=this.source;for(k in a)c[k]=a[k];this.features.push(c)},maybeCreateFeature:function(b,e,a){b<=this.max&&e>=this.min&&this.createFeature(b,e,a)},tramp:function(){if(0==this.blocksToFetch.length)this.callback(this.features);else{var b=this.blocksToFetch[0];if(b.data){var e=new Uint8Array(b.data);if(this.window.isSummary)for(var a=new Int16Array(b.data),c=new Int32Array(b.data),g=new Float32Array(b.data),e=b.data.byteLength/32,a=0;a<e;++a){var d=c[8*
a],b=c[8*a+1],p=c[8*a+2],q=c[8*a+3],j=g[8*a+6];if(d==this.chr){d={score:j/q};if("bigbed"==this.window.bwg.type)d.type="density";this.maybeCreateFeature(b,p,d)}}else if("bigwig"==this.window.bwg.type)if(a=new Int16Array(b.data),c=new Int32Array(b.data),g=new Float32Array(b.data),d=c[0],b=c[1],d=c[3],p=c[4],q=e[20],e=a[11],q==this.BIG_WIG_TYPE_FSTEP)for(a=0;a<e;++a)q=g[a+6],this.maybeCreateFeature(b+a*d,b+a*d+p,{score:q});else if(q==this.BIG_WIG_TYPE_VSTEP)for(a=0;a<e;++a)b=c[2*a+6],q=g[2*a+7],this.maybeCreateFeature(b,
b+p,{score:q});else if(q==this.BIG_WIG_TYPE_GRAPH)for(a=0;a<e;++a)b=c[3*a+6],p=c[3*a+7],q=g[3*a+8],b>p&&(b=p),this.maybeCreateFeature(b,p,{score:q});else n("Currently not handling bwgType="+q);else if("bigbed"==this.window.bwg.type)for(c=0;c<e.length;){d=e[c+3]<<24|e[c+2]<<16|e[c+1]<<8|e[c+0];b=e[c+7]<<24|e[c+6]<<16|e[c+5]<<8|e[c+4];p=e[c+11]<<24|e[c+10]<<16|e[c+9]<<8|e[c+8];c+=12;for(a="";;)if(g=e[c++],0!=g)a+=String.fromCharCode(g);else break;var g={},m=a.split("\t");if(0<m.length)g.label=m[0];
if(1<m.length)g.score=stringToInt(m[1]);if(2<m.length)g.orientation=m[2];if(5<m.length&&(a=m[5],this.window.BED_COLOR_REGEXP.test(a)))g.override_color="rgb("+a+")";if(9>m.length)d==this.chr&&this.maybeCreateFeature(b,p,g);else if(d==this.chr&&b<=this.max&&p>=this.min){p=m[3]|0;d=m[4]|0;a=m[6]|0;q=m[7].split(",");j=m[8].split(",");g.type="bb-transcript";var r=new s;r.id=m[0];r.type="bb-transcript";r.notes=[];g.groups=[r];if(10<m.length){var r=m[9],m=m[10],l=new s;l.id=r;l.label=m;l.type="gene";g.groups.push(l)}m=
null;for(r=0;r<a;++r)l=(j[r]|0)+b,l=new f(l,l+(q[r]|0)),m=m?m.union(l):l;q=m.ranges();for(b=0;b<q.length;++b)a=q[b],this.createFeature(a.min(),a.max(),g);if(d>p&&(b=m.intersection(new f(p,d)))){g.type="bb-translation";p=b.ranges();for(b=0;b<p.length;++b)a=p[b],this.createFeature(a.min(),a.max(),g)}}}else n("Don't know what to do with "+this.window.bwg.type);this.blocksToFetch.splice(0,1);this.tramp()}else{for(var e=b.offset,t=b.size,b=1;b<this.blocksToFetch.length&&this.blocksToFetch[b].offset==e+
t;)t+=this.blocksToFetch[b].size,++b;this.window.bwg.data.slice(e,t).fetch(o.hitch(this,function(a){for(var c=0,b=0;c<t;){var g=this.blocksToFetch[b],d;0<this.window.bwg.uncompressBufSize?d=h(a,c+2,g.size-2):(d=new Uint8Array(g.size),i(new Uint8Array(a,c,g.size),0,d,0,g.size),d=d.buffer);g.data=d;c+=g.size;++b}this.tramp()}),this.errorCallback)}}}})})},"JBrowse/Model/Range":function(){define(["dojo/_base/declare"],function(l){var o=l(null,{constructor:function(){this._ranges=2==arguments.length?[{min:arguments[0],
max:arguments[1]}]:0 in arguments[0]?dojo.clone(arguments[0]):[arguments[0]]},min:function(){return this._ranges[0].min},max:function(){return this._ranges[this._ranges.length-1].max},contains:function(f){for(var h=0;h<this._ranges.length;++h){var i=this._ranges[h];if(i.min<=f&&i.max>=f)return!0}return!1},isContiguous:function(){return 1<this._ranges.length},ranges:function(){return this._ranges.map(function(f){return new o(f.min,f.max)})},toString:function(){return this._ranges.map(function(f){return"["+
f.min+"-"+f.max+"]"}).join(",")},union:function(f){for(var f=this.ranges().concat(f.ranges()).sort(this.rangeOrder),h=[],i=f[0],n=1;n<f.length;++n){var j=f[n];j.min()>i.max()+1?(h.push(i),i=j):j.max()>i.max()&&(i=new o(i.min(),j.max()))}h.push(i);return 1==h.length?h[0]:new _Compound(h)},intersection:function(f){for(var h,i=this.ranges(),n=f.ranges(),j=i.length,l=n.length,s=0,b=0,e=[];s<j&&b<l;){h=i[s];var f=n[b],a=Math.max(h.min(),f.min()),c=Math.min(h.max(),f.max());c>=a&&e.push(new o(a,c));h.max()>
f.max()?++b:++s}return 0==e.length?null:1==e.length?e[0]:new _Compound(e)},coverage:function(){for(var f=0,h=this.ranges(),i=0;i<h.length;++i)var l=h[i],f=f+(l.max()-l.min()+1);return f},rangeOrder:function(f,h){2>arguments.length&&(h=f,f=this);return f.min()<h.min()?-1:f.min()>h.min()?1:f.max()<h.max()?-1:h.max()>f.max()?1:0}});return o})}}});
define("JBrowse/Store/SeqFeature/BigWig","dojo/_base/declare,dojo/_base/lang,dojo/_base/array,dojo/_base/url,JBrowse/has,JBrowse/Store/SeqFeature,JBrowse/Store/DeferredStatsMixin,JBrowse/Store/DeferredFeaturesMixin,./BigWig/Window,JBrowse/Util,JBrowse/Model/XHRBlob".split(","),function(l,o,f,h,i,n,j,u,s,b,e){return l([n,j,u],{BIG_WIG_MAGIC:-2003829722,BIG_BED_MAGIC:-2021002517,BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(a){this.data=a.blob||new e(this.resolveUrl(a.urlTemplate||
"data.bigwig"));this.name=a.name||this.data.url&&(new h(this.data.url)).path.replace(/^.+\//,"")||"anonymous";this._load()},_getGlobalStats:function(a){var c=this._globalStats||{};if(!("scoreMean"in c))c.scoreMean=c.basesCovered?c.scoreSum/c.basesCovered:0;if(!("scoreStdDev"in c))c.scoreStdDev=this._calcStdFromSums(c.scoreSum,c.scoreSumSquares,c.basesCovered);a(c)},_load:function(){var a=this;a.data.slice(0,512).fetch(function(c){if(c){a.fileSize=c.fileSize;var b=new Int16Array(c),d=new Int32Array(c);
if(d[0]==a.BIG_WIG_MAGIC)a.type="bigwig";else if(d[0]==a.BIG_BED_MAGIC)a.type="bigbed";else{console.error("Format "+d[0]+" not supported");a._failAllDeferred("Format "+d[0]+" not supported");return}a.version=b[2];a.numZoomLevels=b[3];a.chromTreeOffset=d[2]<<32|d[3];a.unzoomedDataOffset=d[4]<<32|d[5];a.unzoomedIndexOffset=d[6]<<32|d[7];a.fieldCount=b[16];a.definedFieldCount=b[17];a.asOffset=d[9]<<32|d[10];a.totalSummaryOffset=d[11]<<32|d[12];a.uncompressBufSize=d[13];a.zoomLevels=[];for(b=0;b<a.numZoomLevels;++b)a.zoomLevels.push({reductionLevel:d[6*
b+16],dataOffset:d[6*b+18]<<32|d[6*b+19],indexOffset:d[6*b+20]<<32|d[6*b+21]});a.totalSummaryOffset?Float64Array?function(){var b=new Uint32Array(c,a.totalSummaryOffset,2),d=new Float64Array(c,a.totalSummaryOffset+8,4);a._globalStats={basesCovered:b[0]<<32|b[1],scoreMin:d[0],scoreMax:d[1],scoreSum:d[2],scoreSumSquares:d[3]}}.call():console.warn("BigWig "+a.data.url+" total summary not available, this web browser is not capable of handling this data type."):console.warn("BigWig "+a.data.url+" has no total summary data.");
a._readChromTree(function(){a._deferred.features.resolve({success:!0});a._deferred.stats.resolve({success:!0})},dojo.hitch(a,"_failAllDeferred"))}else this._failAllDeferred("BBI header not readable")},dojo.hitch(this,"_failAllDeferred"))},_readInt:function(a,b){return a[b+3]<<24|a[b+2]<<16|a[b+1]<<8|a[b]},_readShort:function(a,b){return a[b+1]<<8|a[b]},_readChromTree:function(a,b){var g=this;this.refsByNumber={};this.refsByName={};for(var d=this.unzoomedDataOffset;0!=d%4;)++d;var e=this._readInt,
f=this._readShort;this.data.slice(this.chromTreeOffset,d-this.chromTreeOffset).fetch(function(b){if(i("typed-arrays")){var c=new Uint8Array(b),b=new Int32Array(b,0,6);if(2026540177!==b[0])throw"parse error: not a Kent bPlusTree";var d=b[2],h=function(a){if(a>=c.length)throw"reading beyond end of buffer";for(var b=c[a],i=f(c,a+2),a=a+4,l=0;l<i;++l)if(b){for(var j="",n=0;n<d;++n){var o=c[a++];0!=o&&(j+=String.fromCharCode(o))}n=e(c,a);o=e(c,a+4);a+=8;o={name:j,id:n,length:o};g.refsByName[g.browser.regularizeReferenceName(j)]=
o;g.refsByNumber[n]=o}else a+=d,j=e(c,a+4)<<32|e(c,a),a+=8,j-=g.chromTreeOffset,h(j)};h(32);a.call(g,g)}else g._failAllDeferred("Web browser does not support typed arrays")},b)},hasRefSeq:function(a,b,e){var d=this,a=d.browser.regularizeReferenceName(a);this._deferred.features.then(function(){b(a in d.refsByName)},e)},_getFeatures:function(a,b,e,d){var h=this.browser.regularizeReferenceName(a.ref),i=a.start,j=a.end;(a=a.basesPerSpan?this.getView(1/a.basesPerSpan):a.scale?this.getView(scale):this.getView(1))?
a.readWigData(h,i,j,dojo.hitch(this,function(a){f.forEach(a||[],b);e()}),d):e()},getUnzoomedView:function(){if(!this.unzoomedView){var a=4E3;this.zoomLevels[0]&&(a=this.zoomLevels[0].dataOffset-this.unzoomedIndexOffset);this.unzoomedView=new s(this,this.unzoomedIndexOffset,a,!1)}return this.unzoomedView},getView:function(a){if(!this.zoomLevels||!this.zoomLevels.length)return null;if(!this._viewCache||this._viewCache.scale!=a)this._viewCache={scale:a,view:this._getView(a)};return this._viewCache.view},
_getView:function(a){for(var a=1/a,b=this.zoomLevels.length-1;0<b;b--){var e=this.zoomLevels[b];if(e&&e.reductionLevel<=a)return new s(this,e.indexOffset,b<this.zoomLevels.length-1?this.zoomLevels[b+1].dataOffset-e.indexOffset:this.fileSize-4-e.indexOffset,!0)}return this.getUnzoomedView()}})});