#!/usr/bin/env perl

#### EXTERNAL MODULES
use Getopt::Long;
use FindBin qw($Bin);

#### USE LIBS
use lib "$Bin/../lib";

#### INTERNAL MODULES
use Conf::Yaml;
use Queue::Daemon;

#### SET LOG
my $showlog     =   4;
my $printlog    =   4;
my $logfile		=	"/tmp/agua-daemon.$$.log";
my $help;
GetOptions (
    'showlog=i'     => \$showlog,
    'printlog=i'    => \$printlog,
    'help'          => \$help
) or die "No options specified. Try '--help'\n";
usage() if defined $help;

my $conf = Conf::Yaml->new(
    inputfile	  =>	"$Bin/conf/config.yaml",
    backup		  =>	1,
    showlog     =>  2,
    printlog    =>  4
);

my $object      =  Queue::Daemon->new({
    conf        =>  $conf,
    showlog     =>  $showlog,
    printlog    =>  $printlog
});

##############################################################

sub usage {
	print `/usr/bin/env perldoc $0`;
	exit;
}

