---
test:
    TESTUSER:       testuser
    TESTPASSWORD:   testpassword
    TESTDATABASE:   testdatabase

align_nproc_per_lane: 4
align_retries: 2
archive_pending: '/scratch/services/archive/pending'
avg_align_yield_per_lane_Gb: 35
avg_yield_trimmed_gb: 35
bcl_converter_bin: '/development/casava/CASAVA-1.8.3a3/bin/configureBclToFastq.pl'
bcl_nproc_per_lane: 4
bcl_options: '--force --ignore-missing-control --ignore-missing-stats '
build_launch_limit: 5
build_root: '/build/services/Projects'
build_type: local
build_version: NCBI37
data:
    aquarius-8:
        BIOAPPS		        :	/data/apps/bioapps
        HUMAN		        :	/data/sequence/human
        HUMANLATESTBUILD    :	hg19
        JBROWSEDATA	        :	/data/jbrowse/species
        MOUSE		        :	/data/sequence/reference/mouse
        MOUSELATESTBUILD    :	mm9
        RAT		            :	/data/sequence/reference/rat
        RATLATESTBUILD		:	rn4
        SAMTOOLSHUMAN		:	/data/sequence/reference/human/hg19/samtools
        SAMTOOLSMOUSE		:	/data/sequence/reference/mouse/mm9/samtools
        SAMTOOLSRAT		    :	/data/sequence/reference/rat/rn4/samtools
database: wgspipe
dbsnp_version: 131
error_emails:
  - BATMAN@batcave.com
  - ROBIN@batcave.com
error_rate_read1: 1.5
error_rate_read2: 2
estimated_per_align: 80
fasta_locations:
  NCBI36_XX: '/scratch/services/Genomes/FASTA_UCSC/HumanNCBI36_XY/HumanNCBI36_XX.fa'
  NCBI36_XY: '/scratch/services/Genomes/FASTA_UCSC/HumanNCBI36_XY/HumanNCBI36_XY.fa'
  NCBI37_XX: '/scratch/services/Genomes/FASTA_UCSC/HumanNCBI37_XX/HumanNCBI37_XX.fa'
  NCBI37_XY: '/scratch/services/Genomes/FASTA_UCSC/HumanNCBI37_XY/HumanNCBI37_XY.fa'
tools: '/scripts/WGS/tools/bin'
username: billy
